title: curious learner
author: shubham khanna  
email: shubhk9630@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  There are lot of people in this world who want for faster and so that they can learn more.
  so this is page where you can get all kind of learning tips from me and my network.

# social links
twitter_username: cyberkhanna
github_username:  shubhamk06

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
